### ISSUE TITLE
[Bug] Created event with an image does not show up unless array adapter is updated again

### ISSUE THREAD

**Issue by natewu** [CMPUT301W24T27/NoStack#107]
If user creates an event and uploads a picture it will not show the event after it is created unless you go back or create another event (basically updating the view) then it shows up.

Also if you upload a picture on an event with no picture the image does not get updated unless user goes back

**Comment by olsen-adam** [comment]
This bug seems to be due to the fact that we first update the event in the database before we update the event in the view handler. Due to this, we do not have the data as it takes a second for it to update the DB. In the amount of time it takes us to pop to the previous fragment (OrganizerEvent), is faster than the amount of time to load the data from the database. So in a way we are uploading data while also downloading data at the same time, causing the downloading to get the previous event data.

I've tried to implement fixes for this, and nothings working. I'm out of ideas. If someone else could take a look that would be appreciated.

**Comment by olsen-adam** [comment]
![image](https://github.com/CMPUT301W24T27/NoStack/assets/67761974/30ec5e4d-5e2d-4590-bda0-f7110f0d3e72)

If there are any classes that are due to it, it would be these 4

**Comment by natewu** [comment]
if only there was an easy way to handle asynchronous events in Java... @olsen-adam do you think using a callback would work?

**Comment by olsen-adam** [comment]
Fixed by #133
